### ISSUE TITLE
RFE: add support for exporting / importing an ABAP package

### ISSUE THREAD

**Issue by jfilak** [jfilak/sapcli#2]
Start with Classes.

https://abapgit.slack.com/archives/C4K5GM9D0/p1551968395040800

**Comment by jfilak** [comment]
I plan to introduce 2 new commands:
- checkout {class,program,interface,package}
- checkin {class,program,interface,package}

because ABAP platform is sort of a source code repository.
While adding checkout for class, program and interface was trivial (https://github.com/jfilak/sapcli/tree/wip_export_import_aka_checkout_checkin), package requires implementing object traversal first.

**Comment by xtough** [comment]
👍 💯 I guess you already realized that this feature would eventually make abapGIt obsolete: With a CLI for ex-/importing content from/to ABAP Workbench to your local FS, you can use any local Git client to do the actual versioning. ABAP Workbench APIs would become just a deployment channel to a runtime system. Consequentially, ABAP development would become much like any other language.

**Comment by jfilak** [comment]
I've pushed implementation of the checkout for `class`, `interface`, `program`, and `package` with some limitations:
- no abapgit xml metadata file created
- no recursive checkout for sub-packages

For the usage, please consult https://github.com/jfilak/sapcli/blob/master/doc/commands.md#checkout

Any feedback is more than welcome!

**Comment by jfilak** [comment]
I have added the parameters `--starting-folder` and `--recursive` the command `checkout package`.
If you have time, please, test and report the results.

**Comment by xtough** [comment]
works like a charm :-)
some remarks:
- why `--starting-folder` instead of `-o` ?
- why default `--starting-folder` to `src` instead of `<package name>` ?

**Comment by jfilak** [comment]
> why `--starting-folder` instead of `-o` ?

Because I didn't think about it. The nice thing of Python ArgParse is that you can define short option along with long option. I usually start with the long options and add the short options afterwards (I don't know why :).

So, there is a nice opportunity for another patch, just add `'-o', ` before the `'--starting-folder'`.

> why default --starting-folder to src instead of  `<package name>`?

I would say that `checkout package ` should always create a new directory of the name of checked out package (like git clone). The new directory should be populated with `.abagit.xml` and create the same structure as abapgit which has the option `Starting folder` and the source codes are stored there. That means that by default, the starting folder for source codes should be `<package name>/src`

Does that makes sense to you?

**Comment by xtough** [comment]
I agree that `checkout package` should create an abapGit-like folder structure. Apparently `./src` is more or less a constant in this context. I do not see a need to override it to something different. That in turn raises the question what is the semantic of `--starting-folder`. I would vote for the following:
- [ ] change it to `-o <dir>` / `--output-dir <dir>`
- [ ] default it to `.` (cwd)
- [ ] always append `<package name>/src` to `<dir>` so that it basically allows people to redirect output to a different folder but leaves the inner structure of any output stable
- [ ] (optional) make `-o` a global switch for all commands writing some sort of output to the local FS.
What do you think?

**Comment by jfilak** [comment]
Regular abapgit directory has the following structure:
```
PACKAGE/
PACKAGE/.abagit.xml
PACKAGE/src/*.abap
PACKAGE/src/sub-pkg/*.abap
```

I think that `checkout package` should create the file `.abapgit.xml` and that's the reason why we need the option ` --starting-folder` which says where to save source code files in the repo structure.

Basically, we need to know 2 directories:
- repository
- source coudes

```
$ ls -R sool
No such file or directory

$ sapcli checkout sool

$ ls -R sool
sool/.abagit.xml
sool/src/cx_runtime_error.abap
...
```

**Comment by jfilak** [comment]
Checkout the branch `wip_abapgit_like_checkout` and try it out.

**Comment by xtough** [comment]
Now I get it.  I first thought `<STARTING_FOLDER>` was fixed to `src` in abapGit. But since it can be overridden, the parameter makes sense. There is however a bug in your first commit: string replacement is not working in checkout.py so that .abapgit.xml always contains `<STARTING_FOLDER>/{args.starting_folder}/</STARTING_FOLDER>`

My proposal for a global arg `-o` is something different though: It would allow users to stay in whatever CWD they are in and redirect all output of sapcli to some other dir. I have seen this in lots of other CLIs.

**Comment by jfilak** [comment]
As of now, `spacli checkout package { name }` creates the same structure as abapgit for Programs, Classes, Interfaces and Packages. There are some TODOs but it should be possible to checkout a package, git init, git remote add origin, git push and abapgit pull.

Now, I am going to implement `checkin` for all objects used in abapgit: Class, Interface, Program, Fugr, Transaction. The checkin of abapgit will not be straightforward because it requires pre-compilation because of JavaScript and CSS sources that cannot be created via ADT.

**Comment by jfilak** [comment]
Implemented by @palubaj
